const express = require('express')
const app = express()
const Mock = require('mockjs')

app.post('/fn/qc/foster/qcFosterPlanList', function (req, res) {
  const data = {
    code: 0,
    data: {
      list: [
        {
          classId: '1107435',
          className: 'test',
          classStatus: '02002',
          classStatusName: '进行中',
          classTime: '2022-06-09~2022-10-30',
          classAdviser: 'WANGWEN129',
          classAdviserName: '湛箫',
          line: '零售',
          reimDept: 'S000010010',
          reimDeptName: '平安银行零售业务支持部',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02000',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2022-06-09',
          dateEnd: '2022-10-30',
          createdDate: null
        },
        {
          classId: '2114001',
          className: '新的培训班1',
          classStatus: '02002',
          classStatusName: '进行中',
          classTime: '2021-10-18~2022-10-30',
          classAdviser: 'WANGWEN129',
          classAdviserName: '湛箫',
          line: '零售',
          reimDept: 'S000000271',
          reimDeptName: '平安银行信用卡中心',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02001',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-10-18',
          dateEnd: '2022-10-30',
          createdDate: null
        },
        {
          classId: '2114723',
          className: '0809报销测试数据',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2022-08-06~2022-08-09',
          classAdviser: 'ZANGXUE806',
          classAdviserName: '昝瞳',
          line: '零售',
          reimDept: 'S000019288',
          reimDeptName: '平安银行西安分行零售综合管理部业务训战室',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: "'02001",
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2022-08-06',
          dateEnd: '2022-08-09',
          createdDate: null
        },
        {
          classId: '2114390',
          className: '顶测1秀儿专用好家伙好家伙好家伙好家伙好家伙好家伙好家伙好家伙好家伙好家伙好家伙好家伙培训班',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2022-08-01~2022-08-01',
          classAdviser: 'HUANGAJING729',
          classAdviserName: '魏章砚',
          line: '零售',
          reimDept: 'D000023248',
          reimDeptName: '平安银行保险金融事业部',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02000',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2022-08-01',
          dateEnd: '2022-08-01',
          createdDate: null
        },
        {
          classId: '2114691',
          className: '722进行中回归',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2021-12-07~2021-12-07',
          classAdviser: 'WANGWEN129',
          classAdviserName: '湛箫',
          line: '零售',
          reimDept: 'S000000271',
          reimDeptName: '平安银行信用卡中心',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02000',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-12-07',
          dateEnd: '2021-12-07',
          createdDate: null
        },
        {
          classId: '2113988',
          className: '新的培训班1',
          classStatus: '02002',
          classStatusName: '进行中',
          classTime: '2021-07-30~2021-11-25',
          classAdviser: 'WANGWEN129',
          classAdviserName: '湛箫',
          line: '零售',
          reimDept: 'S000000271',
          reimDeptName: '平安银行信用卡中心',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02001',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-07-30',
          dateEnd: '2021-11-25',
          createdDate: null
        },
        {
          classId: '1120135',
          className: '测试验证',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2021-08-18~2021-10-31',
          classAdviser: 'WUJUN003',
          classAdviserName: '米认',
          line: '零售',
          reimDept: 'S000010016',
          reimDeptName: '平安银行零售业务支持部大零售组织能力训战室',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02000',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-08-18',
          dateEnd: '2021-10-31',
          createdDate: null
        },
        {
          classId: '1120215',
          className: '测试验证',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2021-10-13~2021-10-13',
          classAdviser: 'ZHANGYU729',
          classAdviserName: '明符',
          line: '零售',
          reimDept: 'S000010010',
          reimDeptName: '平安银行零售业务支持部',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02000',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-10-13',
          dateEnd: '2021-10-13',
          createdDate: null
        },
        {
          classId: '2113995',
          className: '新的培训班1',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2021-08-31~2021-09-30',
          classAdviser: 'WANGWEN129',
          classAdviserName: '湛箫',
          line: '零售',
          reimDept: 'D000016740',
          reimDeptName: '平安银行综合金融拓展部普惠综拓团队',
          expenseType: 'Y',
          expenseName: '分摊费用',
          classTypeTwo: '02001',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-08-31',
          dateEnd: '2021-09-30',
          createdDate: null
        },
        {
          classId: '2113995',
          className: '新的培训班1',
          classStatus: '02003',
          classStatusName: '已结训',
          classTime: '2021-08-31~2021-09-30',
          classAdviser: 'WANGWEN129',
          classAdviserName: '湛箫',
          line: '零售',
          reimDept: 'S000000271',
          reimDeptName: '平安银行信用卡中心',
          expenseType: 'N',
          expenseName: '举办费用',
          classTypeTwo: '02001',
          classTypeTwoName: null,
          classTypeOpr: null,
          authFlag: null,
          dateStart: '2021-08-31',
          dateEnd: '2021-09-30',
          createdDate: null
        }
      ],
      total: 7619,
      page: 1,
      size: 10
    }
  }
  res.send(data)
})

app.post('/fn/reim/initFast/selectFastClassesInfo', function (req, res) {
  const data = {
    code: 0,
    data: {
      classId: '2114723',
      classAdviser: 'ZANGXUE806',
      reimDept: 'S000019288',
      line: 'LS',
      classTypeTwo: "'02001",
      budgetTotalAmt: '1216000.00',
      payedTotalAmt: '0.00',
      occupyTotalAmt: '239.00',
      budgetTotalAmtChaiLv: null,
      budgetTotalAmtCanZa: null,
      budgetTotalAmtChangZu: null,
      budgetTotalAmtWbpxf: null,
      orgSegment: 'CC01',
      orgDesc: '信用卡中心',
      manageCenterCode: '0879161200',
      manageCenterDesc: '信用卡事业部总部',
      costCenterCode: '0879161001',
      costCenterName: '信用卡总经理室',
      expenseDetails: [
        {
          classId: null,
          expenseType: '000101',
          expenseTypeDescMax: '餐杂费',
          expenseTypeDescMin: '',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '1062',
          feeMinCategoryDesc: '培训-餐费/杂费',
          sortNo: 1,
          budgetAmt: '625000.00',
          occupyAmt: '127.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000501',
          expenseTypeDescMax: '场租及会务费',
          expenseTypeDescMin: '',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '14739',
          feeMinCategoryDesc: '培训-场租及会务费',
          sortNo: 2,
          budgetAmt: '500000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000201',
          expenseTypeDescMax: '外部培训费',
          expenseTypeDescMin: '外部课程研发费用',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16276',
          feeMinCategoryDesc: '外部培训课程研发费用',
          sortNo: 3,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000203',
          expenseTypeDescMax: '外部培训费',
          expenseTypeDescMin: '外派培训费',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16278',
          feeMinCategoryDesc: '外派培训费',
          sortNo: 5,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000204',
          expenseTypeDescMax: '外部培训费',
          expenseTypeDescMin: '资格认证费',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16279',
          feeMinCategoryDesc: '资格认证费',
          sortNo: 6,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000205',
          expenseTypeDescMax: '外部培训费',
          expenseTypeDescMin: '平安大学培训费（移动）',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16282',
          feeMinCategoryDesc: '平安大学培训费-移动',
          sortNo: 7,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000206',
          expenseTypeDescMax: '外部培训费',
          expenseTypeDescMin: '平安大学培训费(面授)',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16281',
          feeMinCategoryDesc: '平安大学培训费-面授',
          sortNo: 8,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000401',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通费',
          expenseTypeDescSmall: '机票-不含民航发展基金',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16271',
          feeMinCategoryDesc: '机票-不含民航发展基金/税率9%',
          sortNo: 9,
          budgetAmt: '5000.00',
          occupyAmt: '112.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '9',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000401',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通费',
          expenseTypeDescSmall: '机票-民航发展基金',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16272',
          feeMinCategoryDesc: '机票-民航发展基金',
          sortNo: 10,
          budgetAmt: '5000.00',
          occupyAmt: '112.00',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000401',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通费',
          expenseTypeDescSmall: '火车票',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16273',
          feeMinCategoryDesc: '火车/网约车/通行费/税率9%',
          sortNo: 11,
          budgetAmt: '5000.00',
          occupyAmt: '112.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '9',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000401',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通费',
          expenseTypeDescSmall: '公路/水路客票（有身份信息）',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16274',
          feeMinCategoryDesc: '公路水路客票/网约车/通行费/税率3%',
          sortNo: 12,
          budgetAmt: '5000.00',
          occupyAmt: '112.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '3',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000401',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通费',
          expenseTypeDescSmall: '差旅培训-其他',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '05013',
          feeMinCategoryDesc: '培训-其他',
          sortNo: 13,
          budgetAmt: '5000.00',
          occupyAmt: '112.00',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000402',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通补助',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '05009',
          feeMinCategoryDesc: '差旅-往返机场车站交通补助费',
          sortNo: 14,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000403',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '住宿费',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '05010',
          feeMinCategoryDesc: '差旅-住宿费',
          sortNo: 15,
          budgetAmt: '25000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '1',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000404',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '交通费（平安大学）',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '05011',
          feeMinCategoryDesc: '平安大学交通费',
          sortNo: 16,
          budgetAmt: '5000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '000405',
          expenseTypeDescMax: '差旅',
          expenseTypeDescMin: '出差补助',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '05012',
          feeMinCategoryDesc: '差旅-其他补助',
          sortNo: 17,
          budgetAmt: '25000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '001001',
          expenseTypeDescMax: '其他费用',
          expenseTypeDescMin: '',
          expenseTypeDescSmall: '',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '05013',
          feeMinCategoryDesc: '培训-其他',
          sortNo: 18,
          budgetAmt: '1000.00',
          occupyAmt: '0.00',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        },
        {
          classId: null,
          expenseType: '001004',
          expenseTypeDescMax: '支付预提费用',
          expenseTypeDescMin: '支付预提-应付款',
          expenseTypeDescSmall: '',
          feeMaxCategory: '36',
          feeMaxCategoryDesc: '支付预提费用',
          feeMinCategory: '36005',
          feeMinCategoryDesc: '2700298支付预提-应付款',
          sortNo: 22,
          budgetAmt: '1216000.00',
          occupyAmt: '800.80',
          payedAmt: '0.00',
          deductionFlag: '0',
          tax: '0',
          accountingSubjectCd: null,
          budgetProjectCode: null
        }
      ],
      supplierStr: '[213143]王文E00010460361|CC01',
      supplierCode: '213143',
      supplierName: '王文E00010460361'
    }
  }
  res.send(data)
})

app.post('/fn/reim/initFast/selectFastReimCity', function (req, res) {
  const data = {
    code: 0,
    data: [
      {
        siteNo: '420000_湖北省',
        siteName: '湖北省',
        children: [
          { siteNo: '420100_武汉市', siteName: '武汉市', children: null },
          { siteNo: '421100_黄冈市', siteName: '黄冈市', children: null },
          { siteNo: '421200_咸宁市', siteName: '咸宁市', children: null },
          { siteNo: '420500_宜昌市', siteName: '宜昌市', children: null },
          { siteNo: '420800_荆门市', siteName: '荆门市', children: null },
          { siteNo: '421300_随州市', siteName: '随州市', children: null },
          { siteNo: '420700_鄂州市', siteName: '鄂州市', children: null },
          { siteNo: '421000_荆州市', siteName: '荆州市', children: null },
          { siteNo: '422800_恩施土家族苗族', siteName: '恩施土家族苗族', children: null },
          { siteNo: '420900_孝感市', siteName: '孝感市', children: null },
          { siteNo: '420200_黄石市', siteName: '黄石市', children: null },
          { siteNo: '420300_十堰市', siteName: '十堰市', children: null },
          { siteNo: '420600_襄阳市', siteName: '襄阳市', children: null }
        ]
      },
      {
        siteNo: '370000_山东省',
        siteName: '山东省',
        children: [
          { siteNo: '370100_济南市', siteName: '济南市', children: null },
          { siteNo: '371100_日照市', siteName: '日照市', children: null },
          { siteNo: '370200_青岛市', siteName: '青岛市', children: null },
          { siteNo: '371600_滨州市', siteName: '滨州市', children: null },
          { siteNo: '371200_莱芜市', siteName: '莱芜市', children: null },
          { siteNo: '370500_东营市', siteName: '东营市', children: null },
          { siteNo: '370900_泰安市', siteName: '泰安市', children: null },
          { siteNo: '370400_枣庄市', siteName: '枣庄市', children: null },
          { siteNo: '370700_潍坊市', siteName: '潍坊市', children: null },
          { siteNo: '371500_聊城市', siteName: '聊城市', children: null },
          { siteNo: '370300_淄博市', siteName: '淄博市', children: null },
          { siteNo: '370600_烟台市', siteName: '烟台市', children: null },
          { siteNo: '371700_菏泽市', siteName: '菏泽市', children: null },
          { siteNo: '371000_威海市', siteName: '威海市', children: null },
          { siteNo: '371300_临沂市', siteName: '临沂市', children: null },
          { siteNo: '371400_德州市', siteName: '德州市', children: null },
          { siteNo: '370800_济宁市', siteName: '济宁市', children: null }
        ]
      },
      {
        siteNo: '220000_吉林省',
        siteName: '吉林省',
        children: [
          { siteNo: '222400_延边朝鲜族自治', siteName: '延边朝鲜族自治', children: null },
          { siteNo: '220600_白山市', siteName: '白山市', children: null },
          { siteNo: '220300_四平市', siteName: '四平市', children: null },
          { siteNo: '220700_松原市', siteName: '松原市', children: null },
          { siteNo: '220800_白城市', siteName: '白城市', children: null },
          { siteNo: '220500_通化市', siteName: '通化市', children: null },
          { siteNo: '220200_吉林市', siteName: '吉林市', children: null },
          { siteNo: '220100_长春市', siteName: '长春市', children: null },
          { siteNo: '220400_辽源市', siteName: '辽源市', children: null }
        ]
      },
      {
        siteNo: '320000_江苏省',
        siteName: '江苏省',
        children: [
          { siteNo: '320800_淮安市', siteName: '淮安市', children: null },
          { siteNo: '321300_宿迁市', siteName: '宿迁市', children: null },
          { siteNo: '320300_徐州市', siteName: '徐州市', children: null },
          { siteNo: '320500_苏州市', siteName: '苏州市', children: null },
          { siteNo: '320400_常州市', siteName: '常州市', children: null },
          { siteNo: '320900_盐城市', siteName: '盐城市', children: null },
          { siteNo: '320600_南通市', siteName: '南通市', children: null },
          { siteNo: '321000_扬州市', siteName: '扬州市', children: null },
          { siteNo: '320100_南京市', siteName: '南京市', children: null },
          { siteNo: '320200_无锡市', siteName: '无锡市', children: null },
          { siteNo: '320700_连云港市', siteName: '连云港市', children: null },
          { siteNo: '321200_泰州市', siteName: '泰州市', children: null }
        ]
      },
      {
        siteNo: '330000_浙江省',
        siteName: '浙江省',
        children: [
          { siteNo: '330500_湖州市', siteName: '湖州市', children: null },
          { siteNo: '330800_衢州市', siteName: '衢州市', children: null },
          { siteNo: '330700_金华市', siteName: '金华市', children: null },
          { siteNo: '330100_杭州市', siteName: '杭州市', children: null },
          { siteNo: '330200_宁波市', siteName: '宁波市', children: null },
          { siteNo: '330300_温州市', siteName: '温州市', children: null },
          { siteNo: '330900_舟山市', siteName: '舟山市', children: null },
          { siteNo: '331100_丽水市', siteName: '丽水市', children: null },
          { siteNo: '330400_嘉兴市', siteName: '嘉兴市', children: null },
          { siteNo: '330600_绍兴市', siteName: '绍兴市', children: null },
          { siteNo: '331000_台州市', siteName: '台州市', children: null }
        ]
      },
      {
        siteNo: '510000_四川省',
        siteName: '四川省',
        children: [
          { siteNo: '511900_巴中市', siteName: '巴中市', children: null },
          { siteNo: '510600_德阳市', siteName: '德阳市', children: null },
          { siteNo: '511100_乐山市', siteName: '乐山市', children: null },
          { siteNo: '510100_成都市', siteName: '成都市', children: null },
          { siteNo: '510400_攀枝花市', siteName: '攀枝花市', children: null },
          { siteNo: '510500_泸州市', siteName: '泸州市', children: null },
          { siteNo: '510700_绵阳市', siteName: '绵阳市', children: null },
          { siteNo: '511300_南充市', siteName: '南充市', children: null },
          { siteNo: '511500_宜宾市', siteName: '宜宾市', children: null },
          { siteNo: '511700_达州市', siteName: '达州市', children: null },
          { siteNo: '513200_阿坝藏族羌族自', siteName: '阿坝藏族羌族自', children: null },
          { siteNo: '510900_遂宁市', siteName: '遂宁市', children: null },
          { siteNo: '511000_内江市', siteName: '内江市', children: null },
          { siteNo: '511600_广安市', siteName: '广安市', children: null },
          { siteNo: '512000_资阳市', siteName: '资阳市', children: null },
          { siteNo: '510300_自贡市', siteName: '自贡市', children: null },
          { siteNo: '510800_广元市', siteName: '广元市', children: null },
          { siteNo: '511400_眉山市', siteName: '眉山市', children: null },
          { siteNo: '511800_雅安市', siteName: '雅安市', children: null },
          { siteNo: '513300_甘孜藏族自治州', siteName: '甘孜藏族自治州', children: null },
          { siteNo: '513400_凉山彝族自治州', siteName: '凉山彝族自治州', children: null }
        ]
      },
      {
        siteNo: '520000_贵州省',
        siteName: '贵州省',
        children: [
          { siteNo: '520200_六盘水市', siteName: '六盘水市', children: null },
          { siteNo: '520300_遵义市', siteName: '遵义市', children: null },
          { siteNo: '522300_黔西南布依族苗', siteName: '黔西南布依族苗', children: null },
          { siteNo: '520100_贵阳市', siteName: '贵阳市', children: null },
          { siteNo: '520500_毕节市', siteName: '毕节市', children: null },
          { siteNo: '520400_安顺市', siteName: '安顺市', children: null },
          { siteNo: '522600_黔东南苗族侗族', siteName: '黔东南苗族侗族', children: null },
          { siteNo: '520600_铜仁市', siteName: '铜仁市', children: null },
          { siteNo: '522700_黔南布依族苗族', siteName: '黔南布依族苗族', children: null }
        ]
      },
      {
        siteNo: '440000_广东省',
        siteName: '广东省',
        children: [
          { siteNo: '440100_广州市', siteName: '广州市', children: null },
          { siteNo: '441300_惠州市', siteName: '惠州市', children: null },
          { siteNo: '440400_珠海市', siteName: '珠海市', children: null },
          { siteNo: '440600_佛山市', siteName: '佛山市', children: null },
          { siteNo: '441500_汕尾市', siteName: '汕尾市', children: null },
          { siteNo: '441700_阳江市', siteName: '阳江市', children: null },
          { siteNo: '445200_揭阳市', siteName: '揭阳市', children: null },
          { siteNo: '440700_江门市', siteName: '江门市', children: null },
          { siteNo: '441900_东莞市', siteName: '东莞市', children: null },
          { siteNo: '440200_韶关市', siteName: '韶关市', children: null },
          { siteNo: '440300_深圳市', siteName: '深圳市', children: null },
          { siteNo: '441200_肇庆市', siteName: '肇庆市', children: null },
          { siteNo: '442000_中山市', siteName: '中山市', children: null },
          { siteNo: '445100_潮州市', siteName: '潮州市', children: null },
          { siteNo: '440800_湛江市', siteName: '湛江市', children: null },
          { siteNo: '445300_云浮市', siteName: '云浮市', children: null },
          { siteNo: '441400_梅州市', siteName: '梅州市', children: null },
          { siteNo: '441800_清远市', siteName: '清远市', children: null },
          { siteNo: '440500_汕头市', siteName: '汕头市', children: null },
          { siteNo: '440900_茂名市', siteName: '茂名市', children: null },
          { siteNo: '441600_河源市', siteName: '河源市', children: null }
        ]
      },
      {
        siteNo: '460000_海南省',
        siteName: '海南省',
        children: [
          { siteNo: '460300_三沙市', siteName: '三沙市', children: null },
          { siteNo: '460200_三亚市', siteName: '三亚市', children: null },
          { siteNo: '460400_儋州市', siteName: '儋州市', children: null },
          { siteNo: '460100_海口市', siteName: '海口市', children: null }
        ]
      },
      {
        siteNo: '640000_宁夏回族自治区',
        siteName: '宁夏回族自治区',
        children: [
          { siteNo: '640400_固原市', siteName: '固原市', children: null },
          { siteNo: '640300_吴忠市', siteName: '吴忠市', children: null },
          { siteNo: '640500_中卫市', siteName: '中卫市', children: null },
          { siteNo: '640100_银川市', siteName: '银川市', children: null },
          { siteNo: '640200_石嘴山市', siteName: '石嘴山市', children: null }
        ]
      },
      {
        siteNo: '430000_湖南省',
        siteName: '湖南省',
        children: [
          { siteNo: '430600_岳阳市', siteName: '岳阳市', children: null },
          { siteNo: '433100_湘西土家族苗族', siteName: '湘西土家族苗族', children: null },
          { siteNo: '430400_衡阳市', siteName: '衡阳市', children: null },
          { siteNo: '430300_湘潭市', siteName: '湘潭市', children: null },
          { siteNo: '430500_邵阳市', siteName: '邵阳市', children: null },
          { siteNo: '430100_长沙市', siteName: '长沙市', children: null },
          { siteNo: '430200_株洲市', siteName: '株洲市', children: null },
          { siteNo: '431100_永州市', siteName: '永州市', children: null },
          { siteNo: '430800_张家界市', siteName: '张家界市', children: null },
          { siteNo: '431000_郴州市', siteName: '郴州市', children: null },
          { siteNo: '430700_常德市', siteName: '常德市', children: null },
          { siteNo: '431300_娄底市', siteName: '娄底市', children: null },
          { siteNo: '431200_怀化市', siteName: '怀化市', children: null }
        ]
      },
      {
        siteNo: '810000_香港特别行政区',
        siteName: '香港特别行政区',
        children: [{ siteNo: '810000_香港特别行政区', siteName: '香港特别行政区', children: null }]
      },
      {
        siteNo: '530000_云南省',
        siteName: '云南省',
        children: [
          { siteNo: '530600_昭通市', siteName: '昭通市', children: null },
          { siteNo: '533300_怒江傈僳族自治', siteName: '怒江傈僳族自治', children: null },
          { siteNo: '530800_普洱市', siteName: '普洱市', children: null },
          { siteNo: '533100_德宏傣族景颇族', siteName: '德宏傣族景颇族', children: null },
          { siteNo: '530500_保山市', siteName: '保山市', children: null },
          { siteNo: '530700_丽江市', siteName: '丽江市', children: null },
          { siteNo: '532900_大理白族自治州', siteName: '大理白族自治州', children: null },
          { siteNo: '533400_迪庆藏族自治州', siteName: '迪庆藏族自治州', children: null },
          { siteNo: '530300_曲靖市', siteName: '曲靖市', children: null },
          { siteNo: '530400_玉溪市', siteName: '玉溪市', children: null },
          { siteNo: '532500_红河哈尼族彝族', siteName: '红河哈尼族彝族', children: null },
          { siteNo: '532300_楚雄彝族自治州', siteName: '楚雄彝族自治州', children: null },
          { siteNo: '532600_文山壮族苗族自', siteName: '文山壮族苗族自', children: null },
          { siteNo: '530100_昆明市', siteName: '昆明市', children: null },
          { siteNo: '530900_临沧市', siteName: '临沧市', children: null },
          { siteNo: '532800_西双版纳傣族自', siteName: '西双版纳傣族自', children: null }
        ]
      },
      {
        siteNo: '610000_陕西省',
        siteName: '陕西省',
        children: [
          { siteNo: '610200_铜川市', siteName: '铜川市', children: null },
          { siteNo: '610600_延安市', siteName: '延安市', children: null },
          { siteNo: '610400_咸阳市', siteName: '咸阳市', children: null },
          { siteNo: '610300_宝鸡市', siteName: '宝鸡市', children: null },
          { siteNo: '610500_渭南市', siteName: '渭南市', children: null },
          { siteNo: '610800_榆林市', siteName: '榆林市', children: null },
          { siteNo: '610900_安康市', siteName: '安康市', children: null },
          { siteNo: '610100_西安市', siteName: '西安市', children: null },
          { siteNo: '611000_商洛市', siteName: '商洛市', children: null },
          { siteNo: '610700_汉中市', siteName: '汉中市', children: null }
        ]
      },
      {
        siteNo: '620000_甘肃省',
        siteName: '甘肃省',
        children: [
          { siteNo: '620600_武威市', siteName: '武威市', children: null },
          { siteNo: '620700_张掖市', siteName: '张掖市', children: null },
          { siteNo: '620800_平凉市', siteName: '平凉市', children: null },
          { siteNo: '621000_庆阳市', siteName: '庆阳市', children: null },
          { siteNo: '621200_陇南市', siteName: '陇南市', children: null },
          { siteNo: '620400_白银市', siteName: '白银市', children: null },
          { siteNo: '623000_甘南藏族自治州', siteName: '甘南藏族自治州', children: null },
          { siteNo: '620200_嘉峪关市', siteName: '嘉峪关市', children: null },
          { siteNo: '620300_金昌市', siteName: '金昌市', children: null },
          { siteNo: '622900_临夏回族自治州', siteName: '临夏回族自治州', children: null },
          { siteNo: '620500_天水市', siteName: '天水市', children: null },
          { siteNo: '620900_酒泉市', siteName: '酒泉市', children: null },
          { siteNo: '621100_定西市', siteName: '定西市', children: null },
          { siteNo: '620100_兰州市', siteName: '兰州市', children: null }
        ]
      },
      {
        siteNo: '130000_河北省',
        siteName: '河北省',
        children: [
          { siteNo: '130200_唐山市', siteName: '唐山市', children: null },
          { siteNo: '130300_秦皇岛市', siteName: '秦皇岛市', children: null },
          { siteNo: '130600_保定市', siteName: '保定市', children: null },
          { siteNo: '130900_沧州市', siteName: '沧州市', children: null },
          { siteNo: '131100_衡水市', siteName: '衡水市', children: null },
          { siteNo: '130100_石家庄市', siteName: '石家庄市', children: null },
          { siteNo: '130500_邢台市', siteName: '邢台市', children: null },
          { siteNo: '130700_张家口市', siteName: '张家口市', children: null },
          { siteNo: '130400_邯郸市', siteName: '邯郸市', children: null },
          { siteNo: '131000_廊坊市', siteName: '廊坊市', children: null },
          { siteNo: '130800_承德市', siteName: '承德市', children: null }
        ]
      },
      {
        siteNo: '140000_山西省',
        siteName: '山西省',
        children: [
          { siteNo: '140100_太原市', siteName: '太原市', children: null },
          { siteNo: '140600_朔州市', siteName: '朔州市', children: null },
          { siteNo: '140300_阳泉市', siteName: '阳泉市', children: null },
          { siteNo: '140700_晋中市', siteName: '晋中市', children: null },
          { siteNo: '140800_运城市', siteName: '运城市', children: null },
          { siteNo: '140500_晋城市', siteName: '晋城市', children: null },
          { siteNo: '140200_大同市', siteName: '大同市', children: null },
          { siteNo: '140400_长治市', siteName: '长治市', children: null },
          { siteNo: '140900_忻州市', siteName: '忻州市', children: null },
          { siteNo: '141000_临汾市', siteName: '临汾市', children: null },
          { siteNo: '141100_吕梁市', siteName: '吕梁市', children: null }
        ]
      },
      {
        siteNo: '210000_辽宁省',
        siteName: '辽宁省',
        children: [
          { siteNo: '211000_辽阳市', siteName: '辽阳市', children: null },
          { siteNo: '211200_铁岭市', siteName: '铁岭市', children: null },
          { siteNo: '211400_葫芦岛市', siteName: '葫芦岛市', children: null },
          { siteNo: '210500_本溪市', siteName: '本溪市', children: null },
          { siteNo: '210600_丹东市', siteName: '丹东市', children: null },
          { siteNo: '210900_阜新市', siteName: '阜新市', children: null },
          { siteNo: '210200_大连市', siteName: '大连市', children: null },
          { siteNo: '210700_锦州市', siteName: '锦州市', children: null },
          { siteNo: '210800_营口市', siteName: '营口市', children: null },
          { siteNo: '210400_抚顺市', siteName: '抚顺市', children: null },
          { siteNo: '211300_朝阳市', siteName: '朝阳市', children: null },
          { siteNo: '210300_鞍山市', siteName: '鞍山市', children: null },
          { siteNo: '211100_盘锦市', siteName: '盘锦市', children: null },
          { siteNo: '210100_沈阳市', siteName: '沈阳市', children: null }
        ]
      },
      {
        siteNo: '150000_内蒙古自治区',
        siteName: '内蒙古自治区',
        children: [
          { siteNo: '150100_呼和浩特市', siteName: '呼和浩特市', children: null },
          { siteNo: '150700_呼伦贝尔市', siteName: '呼伦贝尔市', children: null },
          { siteNo: '152200_兴安盟', siteName: '兴安盟', children: null },
          { siteNo: '150300_乌海市', siteName: '乌海市', children: null },
          { siteNo: '150600_鄂尔多斯市', siteName: '鄂尔多斯市', children: null },
          { siteNo: '150800_巴彦淖尔市', siteName: '巴彦淖尔市', children: null },
          { siteNo: '152500_锡林郭勒盟', siteName: '锡林郭勒盟', children: null },
          { siteNo: '150400_赤峰市', siteName: '赤峰市', children: null },
          { siteNo: '150500_通辽市', siteName: '通辽市', children: null },
          { siteNo: '152900_阿拉善盟', siteName: '阿拉善盟', children: null },
          { siteNo: '150900_乌兰察布市', siteName: '乌兰察布市', children: null },
          { siteNo: '150200_包头市', siteName: '包头市', children: null }
        ]
      },
      {
        siteNo: '360000_江西省',
        siteName: '江西省',
        children: [
          { siteNo: '360100_南昌市', siteName: '南昌市', children: null },
          { siteNo: '360200_景德镇市', siteName: '景德镇市', children: null },
          { siteNo: '360300_萍乡市', siteName: '萍乡市', children: null },
          { siteNo: '360700_赣州市', siteName: '赣州市', children: null },
          { siteNo: '361100_上饶市', siteName: '上饶市', children: null },
          { siteNo: '360600_鹰潭市', siteName: '鹰潭市', children: null },
          { siteNo: '360500_新余市', siteName: '新余市', children: null },
          { siteNo: '360400_九江市', siteName: '九江市', children: null },
          { siteNo: '360800_吉安市', siteName: '吉安市', children: null },
          { siteNo: '361000_抚州市', siteName: '抚州市', children: null },
          { siteNo: '360900_宜春市', siteName: '宜春市', children: null }
        ]
      },
      {
        siteNo: '410000_河南省',
        siteName: '河南省',
        children: [
          { siteNo: '410200_开封市', siteName: '开封市', children: null },
          { siteNo: '410500_安阳市', siteName: '安阳市', children: null },
          { siteNo: '410700_新乡市', siteName: '新乡市', children: null },
          { siteNo: '411400_商丘市', siteName: '商丘市', children: null },
          { siteNo: '419001_济源市', siteName: '济源市', children: null },
          { siteNo: '410400_平顶山市', siteName: '平顶山市', children: null },
          { siteNo: '411600_周口市', siteName: '周口市', children: null },
          { siteNo: '411700_驻马店市', siteName: '驻马店市', children: null },
          { siteNo: '410300_洛阳市', siteName: '洛阳市', children: null },
          { siteNo: '411200_三门峡市', siteName: '三门峡市', children: null },
          { siteNo: '411100_漯河市', siteName: '漯河市', children: null },
          { siteNo: '411300_南阳市', siteName: '南阳市', children: null },
          { siteNo: '411500_信阳市', siteName: '信阳市', children: null },
          { siteNo: '410100_郑州市', siteName: '郑州市', children: null },
          { siteNo: '410600_鹤壁市', siteName: '鹤壁市', children: null },
          { siteNo: '410800_焦作市', siteName: '焦作市', children: null },
          { siteNo: '410900_濮阳市', siteName: '濮阳市', children: null }
        ]
      },
      {
        siteNo: '230000_黑龙江省',
        siteName: '黑龙江省',
        children: [
          { siteNo: '230300_鸡西市', siteName: '鸡西市', children: null },
          { siteNo: '231200_绥化市', siteName: '绥化市', children: null },
          { siteNo: '232700_大兴安岭地区', siteName: '大兴安岭地区', children: null },
          { siteNo: '230900_七台河市', siteName: '七台河市', children: null },
          { siteNo: '230200_齐齐哈尔市', siteName: '齐齐哈尔市', children: null },
          { siteNo: '230400_鹤岗市', siteName: '鹤岗市', children: null },
          { siteNo: '230600_大庆市', siteName: '大庆市', children: null },
          { siteNo: '230700_伊春市', siteName: '伊春市', children: null },
          { siteNo: '231100_黑河市', siteName: '黑河市', children: null },
          { siteNo: '230100_哈尔滨市', siteName: '哈尔滨市', children: null },
          { siteNo: '230500_双鸭山市', siteName: '双鸭山市', children: null },
          { siteNo: '230800_佳木斯市', siteName: '佳木斯市', children: null },
          { siteNo: '231000_牡丹江市', siteName: '牡丹江市', children: null }
        ]
      },
      {
        siteNo: '340000_安徽省',
        siteName: '安徽省',
        children: [
          { siteNo: '340700_铜陵市', siteName: '铜陵市', children: null },
          { siteNo: '340800_安庆市', siteName: '安庆市', children: null },
          { siteNo: '341300_宿州市', siteName: '宿州市', children: null },
          { siteNo: '341700_池州市', siteName: '池州市', children: null },
          { siteNo: '341000_黄山市', siteName: '黄山市', children: null },
          { siteNo: '340500_马鞍山市', siteName: '马鞍山市', children: null },
          { siteNo: '340100_合肥市', siteName: '合肥市', children: null },
          { siteNo: '340200_芜湖市', siteName: '芜湖市', children: null },
          { siteNo: '340600_淮北市', siteName: '淮北市', children: null },
          { siteNo: '341600_亳州市', siteName: '亳州市', children: null },
          { siteNo: '340400_淮南市', siteName: '淮南市', children: null },
          { siteNo: '341500_六安市', siteName: '六安市', children: null },
          { siteNo: '340300_蚌埠市', siteName: '蚌埠市', children: null },
          { siteNo: '341100_滁州市', siteName: '滁州市', children: null },
          { siteNo: '341200_阜阳市', siteName: '阜阳市', children: null },
          { siteNo: '341800_宣城市', siteName: '宣城市', children: null }
        ]
      },
      {
        siteNo: '450000_广西壮族自治区',
        siteName: '广西壮族自治区',
        children: [
          { siteNo: '450400_梧州市', siteName: '梧州市', children: null },
          { siteNo: '451400_崇左市', siteName: '崇左市', children: null },
          { siteNo: '450900_玉林市', siteName: '玉林市', children: null },
          { siteNo: '451300_来宾市', siteName: '来宾市', children: null },
          { siteNo: '450500_北海市', siteName: '北海市', children: null },
          { siteNo: '450600_防城港市', siteName: '防城港市', children: null },
          { siteNo: '450800_贵港市', siteName: '贵港市', children: null },
          { siteNo: '451100_贺州市', siteName: '贺州市', children: null },
          { siteNo: '450300_桂林市', siteName: '桂林市', children: null },
          { siteNo: '450200_柳州市', siteName: '柳州市', children: null },
          { siteNo: '450700_钦州市', siteName: '钦州市', children: null },
          { siteNo: '451000_百色市', siteName: '百色市', children: null },
          { siteNo: '450100_南宁市', siteName: '南宁市', children: null },
          { siteNo: '451200_河池市', siteName: '河池市', children: null }
        ]
      },
      {
        siteNo: '650000_新疆维吾尔自治',
        siteName: '新疆维吾尔自治',
        children: [
          { siteNo: '652700_博尔塔拉蒙古自', siteName: '博尔塔拉蒙古自', children: null },
          { siteNo: '652800_巴音郭楞蒙古自', siteName: '巴音郭楞蒙古自', children: null },
          { siteNo: '653000_克孜勒苏柯尔克', siteName: '克孜勒苏柯尔克', children: null },
          { siteNo: '652300_昌吉回族自治州', siteName: '昌吉回族自治州', children: null },
          { siteNo: '650500_哈密市', siteName: '哈密市', children: null },
          { siteNo: '652900_阿克苏地区', siteName: '阿克苏地区', children: null },
          { siteNo: '654000_伊犁哈萨克自治', siteName: '伊犁哈萨克自治', children: null },
          { siteNo: '650400_吐鲁番市', siteName: '吐鲁番市', children: null },
          { siteNo: '654200_塔城地区', siteName: '塔城地区', children: null },
          { siteNo: '654300_阿勒泰地区', siteName: '阿勒泰地区', children: null },
          { siteNo: '650100_乌鲁木齐市', siteName: '乌鲁木齐市', children: null },
          { siteNo: '653100_喀什地区', siteName: '喀什地区', children: null },
          { siteNo: '653200_和田地区', siteName: '和田地区', children: null },
          { siteNo: '650200_克拉玛依市', siteName: '克拉玛依市', children: null }
        ]
      },
      {
        siteNo: '350000_福建省',
        siteName: '福建省',
        children: [
          { siteNo: '350700_南平市', siteName: '南平市', children: null },
          { siteNo: '350800_龙岩市', siteName: '龙岩市', children: null },
          { siteNo: '350900_宁德市', siteName: '宁德市', children: null },
          { siteNo: '350400_三明市', siteName: '三明市', children: null },
          { siteNo: '350600_漳州市', siteName: '漳州市', children: null },
          { siteNo: '350300_莆田市', siteName: '莆田市', children: null },
          { siteNo: '350100_福州市', siteName: '福州市', children: null },
          { siteNo: '350500_泉州市', siteName: '泉州市', children: null },
          { siteNo: '350200_厦门市', siteName: '厦门市', children: null }
        ]
      },
      {
        siteNo: '630000_青海省',
        siteName: '青海省',
        children: [
          { siteNo: '632800_海西蒙古族藏族', siteName: '海西蒙古族藏族', children: null },
          { siteNo: '630200_海东市', siteName: '海东市', children: null },
          { siteNo: '632500_海南藏族自治州', siteName: '海南藏族自治州', children: null },
          { siteNo: '632600_果洛藏族自治州', siteName: '果洛藏族自治州', children: null },
          { siteNo: '632700_玉树藏族自治州', siteName: '玉树藏族自治州', children: null },
          { siteNo: '630100_西宁市', siteName: '西宁市', children: null },
          { siteNo: '632300_黄南藏族自治州', siteName: '黄南藏族自治州', children: null },
          { siteNo: '632200_海北藏族自治州', siteName: '海北藏族自治州', children: null }
        ]
      },
      {
        siteNo: '540000_西藏自治区',
        siteName: '西藏自治区',
        children: [
          { siteNo: '540300_昌都市', siteName: '昌都市', children: null },
          { siteNo: '540200_日喀则市', siteName: '日喀则市', children: null },
          { siteNo: '540400_林芝市', siteName: '林芝市', children: null },
          { siteNo: '542500_阿里地区', siteName: '阿里地区', children: null },
          { siteNo: '540100_拉萨市', siteName: '拉萨市', children: null },
          { siteNo: '540500_山南市', siteName: '山南市', children: null }
        ]
      },
      {
        siteNo: '820000_澳门特别行政区',
        siteName: '澳门特别行政区',
        children: [{ siteNo: '820000_澳门特别行政区', siteName: '澳门特别行政区', children: null }]
      },
      { siteNo: '310000_上海市', siteName: '上海市', children: [{ siteNo: '310000_上海市', siteName: '上海市', children: null }] },
      { siteNo: '110000_北京市', siteName: '北京市', children: [{ siteNo: '110000_北京市', siteName: '北京市', children: null }] },
      { siteNo: '120000_天津市', siteName: '天津市', children: [{ siteNo: '120000_天津市', siteName: '天津市', children: null }] },
      { siteNo: '710000_台湾省', siteName: '台湾省', children: [{ siteNo: '710000_台湾省', siteName: '台湾省', children: null }] }
    ]
  }
  res.send(data)
})
app.post('/fn/reim/initFast/selectFastReimSupplier', function (req, res) {
  const data = {
    code: 0,
    data: {
      list: [
        {
          supplierCode: '213143',
          supplierName: '王文E00010460361',
          taxpayer: null,
          orgSegment: 'CC01',
          orgSegmentDesc: '信用卡中心',
          addrName: '办公室',
          accountInfo: '6216260000016936081',
          residentDescFlag: '居民',
          supplierTypeDesc: '员工供应商',
          payAmt: null,
          reimSupplier: {
            createdBy: null,
            updatedBy: null,
            createdDate: null,
            updatedDate: null,
            id: 0,
            reimId: null,
            serialNo: null,
            payeeType: '01',
            payeeName: '王文E00010460361',
            payeeCode: '213143',
            payeePlaceLayerNo: '140837',
            payeePlaceLayerName: '办公室',
            acctOpenName: '王文E00010460361',
            accountInfo: '6216260000016936081',
            acctOpenBranchInfo: '平安银行上海市分行',
            bankPaySummary: null,
            payAmt: null,
            payAcctName: '455042',
            corOfSupplierNo: '213143',
            ofSupplierId: '325539',
            supplierTypeDesc: '员工供应商',
            orgSegment: 'CC01',
            orgSegmentDesc: '信用卡中心',
            residentDescFlag: '居民',
            primaryFlag: null
          },
          supplierStr: '[213143]王文E00010460361|CC01'
        }
      ],
      total: 1,
      page: 1,
      size: 10
    }
  }
  res.send(data)
})
app.post('/fn/reim/initFast/selectFastReimAccountingSubjectCds', function (req, res) {
  const data = {
    code: 0,
    data: [
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        maxCategoryCode: '5',
        maxCategoryName: null,
        minCategoryCode: '16273',
        minCategoryName: null,
        costType: '1',
        suspendMaxCategory: null,
        suspendMaxCategoryDesc: null,
        suspendMinCategory: null,
        suspendMinCategoryDesc: null,
        accountingSubjectCd: '5320501',
        budgetProjectCode: 'B010804',
        taxRate: '9'
      }
    ]
  }
  res.send(data)
})
app.post('/fn/reim/initFast/selectFastCostCenter', function (req, res) {
  const data = {
    code: 0,
    data: {
      list: [
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161900',
          costCenterName: '资产出表团队',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161901',
          costCenterName: '实物商城平台团队',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161902',
          costCenterName: '互联网获客部（停用）',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161903',
          costCenterName: '客户经营价值团队',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161904',
          costCenterName: '营销及品牌管理团队',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161013',
          costCenterName: '获客研发团队（停用）',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161014',
          costCenterName: '风险研发团队',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161009',
          costCenterName: '战略规划部',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161011',
          costCenterName: '法律合规部',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        },
        {
          deptId: null,
          deptDesc: null,
          orgId: null,
          orgSegment: 'CC01',
          orgDesc: '信用卡中心',
          manageCenterCode: '0879161200',
          manageCenterDesc: '信用卡事业部总部',
          costCenterCode: '0879161012',
          costCenterName: '行政部',
          supplierStr: null,
          supplierCode: null,
          supplierName: null
        }
      ],
      total: 42,
      page: 1,
      size: 10
    }
  }
  res.send(data)
})
app.post('/fn/reim/initFast/insertFastReimForSave', function (req, res) {
  const data = { code: 0, data: { code: '0', msg: '操作成功', t: '16693686049556371755' } }
  res.send(data)
})
app.post('/fn/reim/self/selectMyReimburseList', function (req, res) {
  const data = {
    code: 0,
    data: {
      list: [
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16693686049556371755',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 17:30:35'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16692837634129903339',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 14:52:45'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16693442549353710055',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '3000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 10:49:59'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16693438774915363701',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 10:37:57'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16693431947504200752',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 10:26:35'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16693417371110137797',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 10:17:17'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16693411216085145658',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '0.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 09:52:02'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16692878023507572554',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-25 09:11:39'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16692868235878106650',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-24 18:47:04'
        },
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          reimId: '16692859759114824264',
          reimIdFas: '',
          classId: '2114723',
          className: '0809报销测试数据',
          classAdviser: null,
          classAdviserName: '昝瞳',
          operName: null,
          operUm: null,
          operOrgCode: null,
          operOrgName: null,
          orgSegment: null,
          orgDesc: null,
          manageCenterCode: null,
          manageCenterDesc: null,
          costCenterCode: null,
          costCenterName: null,
          remark: null,
          reimDuePayAmt: null,
          reimTotalAmt: '1000.00',
          suspendAmt: null,
          cnclAmt: null,
          reimOper: null,
          supplierId: null,
          supplierCode: null,
          supplierName: null,
          placeLayerId: null,
          supplierAcctOpenName: null,
          payeeSupplierStr: null,
          operate: null,
          reimStatus: '00',
          applyStatus: null,
          reimSubmitDate: null,
          reimClassType: null,
          reimFinalAmt: '0.00',
          reimType: null,
          ifShare: 'N',
          delFlag: null,
          blgStripLine: null,
          line: '零售',
          reimDept: 'S000019288',
          isFastReim: 'Y',
          afterRepairFlag: null,
          reimStatusName: '未提交',
          dataFunc: '3',
          expenseDate: '2022-11-24 18:39:10'
        }
      ],
      total: 225,
      page: 1,
      size: 10
    }
  }
  res.send(data)
})
app.post('/fn/reim/self/selectReimDicts', function (req, res) {
  const data = {
    code: 0,
    data: [
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '00',
        dataValue: '未提交',
        pageSort: '24',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '3'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '01',
        dataValue: '已保存',
        pageSort: '1',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '02',
        dataValue: '待匹配扫描影像',
        pageSort: '2',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '03',
        dataValue: '费用审批中',
        pageSort: '3',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '04',
        dataValue: '已退回',
        pageSort: '4',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '2'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '05',
        dataValue: '经办人撤回',
        pageSort: '5',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '3'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '06',
        dataValue: '远程作业处理中',
        pageSort: '6',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '07',
        dataValue: '支付中',
        pageSort: '7',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '08',
        dataValue: '支付完成',
        pageSort: '8',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '09',
        dataValue: '已作废',
        pageSort: '9',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '2'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '10',
        dataValue: '待重新扫描（中心退回）',
        pageSort: '10',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '11',
        dataValue: '待重新扫描（财务部退回）',
        pageSort: '11',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '12',
        dataValue: '预算占用中',
        pageSort: '12',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '13',
        dataValue: '预算占用失败退回',
        pageSort: '13',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '2'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '14',
        dataValue: 'EOA审批中',
        pageSort: '14',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '15',
        dataValue: '审批完成',
        pageSort: '15',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '16',
        dataValue: '正在导入OF中',
        pageSort: '16',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '17',
        dataValue: '流程启动失败退回',
        pageSort: '17',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '2'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '19',
        dataValue: '报账支付失败',
        pageSort: '19',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '20',
        dataValue: '导入OF失败',
        pageSort: '20',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '21',
        dataValue: '预算占用切换中',
        pageSort: '21',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '22',
        dataValue: '预算释放失败',
        pageSort: '22',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '23',
        dataValue: '预算占用失败',
        pageSort: '23',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: '24',
        dataValue: '预算占用切换成功',
        pageSort: '24',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '0'
      },
      {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        id: null,
        dataCtgy: 'reim_status',
        dataEncode: 'T02',
        dataValue: '提交失败',
        pageSort: '25',
        prnDataEncode: '',
        ifValid: 'Y',
        dataDesc: '',
        dataFunc: '3'
      }
    ]
  }
  res.send(data)
})
app.post('/fn/reim/selfFast/selectFastReimInfoForUpdate', function (req, res) {
  const data = {
    code: 0,
    data: {
      suspends: [],
      cancels: [],
      suppliers: [],
      consultInfos: null,
      trips: [],
      details: [
        {
          createdBy: null,
          updatedBy: null,
          createdDate: null,
          updatedDate: null,
          id: 743306,
          reimId: null,
          reimBranchId: 'tms2114723166936863542599096990',
          rowIndex: 1,
          classId: '2114723',
          expenseType: '000401',
          feeMaxCategory: '5',
          feeMaxCategoryDesc: '培训费',
          feeMinCategory: '16273',
          feeMinCategoryDesc: '火车/网约车/通行费/税率9%',
          classBudgetAmt: '5000.00',
          payedAmt: '0.00',
          occupyAmt: '112.00',
          amt: '1000.00',
          taxAmt: '82.57',
          excludingTaxAmt: '917.43',
          remark: '',
          reimLineFinalAmt: '0.00',
          syncFlag: null,
          deductionFlag: '1',
          accountingSubjectCd: '5320501',
          budgetProjectCode: 'B010804',
          budgetProjectName: '',
          payDate: null,
          projectCode: '0',
          projectName: '空值',
          productCode: '0',
          productName: '空值',
          kuOrderNo: '0',
          kuOrderName: '空值',
          taxRate: '9',
          invoices: [],
          caikuOrder: null,
          splitInfo: [
            {
              createdBy: null,
              updatedBy: null,
              createdDate: null,
              updatedDate: null,
              id: null,
              reimId: null,
              reimBranchId: null,
              manageCenterCode: '0879161200',
              manageCenterDesc: '信用卡事业部总部',
              costCenterCode: '0879161001',
              costCenterName: '信用卡总经理室',
              totalPriceTax: '500.00',
              excludingTaxAmt: '458.72',
              tax: '9.00',
              projectCode: '0',
              projectName: '空值',
              productCode: '0',
              productName: '空值',
              kuOrderNo: '0',
              kuOrderName: '空值'
            },
            {
              createdBy: null,
              updatedBy: null,
              createdDate: null,
              updatedDate: null,
              id: null,
              reimId: null,
              reimBranchId: null,
              manageCenterCode: '0879161200',
              manageCenterDesc: '信用卡事业部总部',
              costCenterCode: '0879161900',
              costCenterName: '资产出表团队',
              totalPriceTax: '500.00',
              excludingTaxAmt: '458.72',
              tax: '9.00',
              projectCode: '0',
              projectName: '空值',
              productCode: '0',
              productName: '空值',
              kuOrderNo: '0',
              kuOrderName: '空值'
            }
          ]
        }
      ],
      contracts: [],
      primary: {
        createdBy: null,
        updatedBy: null,
        createdDate: null,
        updatedDate: null,
        reimId: null,
        reimIdFas: '',
        classId: '2114723',
        className: '0809报销测试数据',
        classAdviser: 'ZANGXUE806',
        classAdviserName: '昝瞳',
        operName: '湛箫',
        operUm: 'WANGWEN129',
        operOrgCode: 'S000000271',
        operOrgName: '平安银行信用卡中心',
        orgSegment: 'CC01',
        orgDesc: '信用卡中心',
        manageCenterCode: '0879161200',
        manageCenterDesc: '信用卡事业部总部',
        costCenterCode: '0879161001',
        costCenterName: '信用卡总经理室',
        remark: '',
        reimDuePayAmt: '1000.00',
        reimTotalAmt: '1000.00',
        suspendAmt: '0.00',
        cnclAmt: '0.00',
        reimOper: 'submit',
        supplierId: '325539',
        supplierCode: '213143',
        supplierName: '王文E00010460361',
        placeLayerId: '',
        supplierAcctOpenName: '平安银行上海市分行',
        payeeSupplierStr: '[213143]王文E00010460361|CC01',
        operate: '01',
        reimStatus: '未提交',
        applyStatus: '未审批',
        reimSubmitDate: '2022-11-25',
        reimClassType: '1',
        reimFinalAmt: '0.00',
        reimType: 'PT',
        ifShare: 'N',
        delFlag: null,
        blgStripLine: 'LS',
        line: 'LS',
        reimDept: 'S000019288',
        isFastReim: 'Y',
        afterRepairFlag: null,
        reimStatusCode: '00',
        classTypeOne: null,
        classBudgetTotalAmt: null,
        occupyTotalAmt: null,
        payedTotalAmt: null,
        reimSubmitDateFormat: null,
        reportClassName: null,
        reportClassId: null,
        reportClassAdviserName: null,
        reportIfShare: null,
        reportOperName: null,
        reportReimIdFas: null,
        reportReimDuePayAmt: null
      },
      attaches: []
    }
  }
  res.send(data)
})
app.post('/fn/reim/initFast/selectFastClassesInfo', function (req, res) {
  const data = {}
  res.send(data)
})